
# version: "3.9"

services:
  # db:
  #   image: postgres:15
  #   container_name: DATABASE
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: gautamcognine
  #     POSTGRES_DB: mytestdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: API
    # restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node server.js"

# volumes:
#   pgdata:

# docker run -d --name ap_image -p 3000:3000 -e DATABASE_URL="postgresql://postgres:gautamcognine@host.docker.internal:5432/mytestdb" prisma-api sh -c "npx prisma generate && node server.js"
#  use this command to run a new container witht he same image . 